server:
  port: 8989

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: etudiant-service-api
          uri: lb://ETUDIANT-SERVICE-API
          predicates:
            - Path=/etudiant/**
        - id: examen-api
          uri: lb://EXAMEN-API
          predicates:
            - Path=/moyenne/**
        - id: service-admission
          uri: lb://SERVICE-ADMISSION
          predicates:
            - Path=/admission/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: eureka-server
