pipeline{
    agent any
    tools{
        maven "3.9.4"
    }
    stages{
        stage('Source') {
            steps{
                git branch: 'main', url: 'https://github.com/bayembacke221/microservice-docker-cicd-kubernetes.git'
            }
        }
        stage ('Build') {
            steps{
                bat 'mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -f "service-inscription/pom.xml"'
            }
        }
        stage ('SonarQube Analysis') {
            steps{
                bat 'mvn sonar:sonar -f "service-inscription/pom.xml"'
            }
        }
       /** stage('Build image docker') {

            steps {
                bat 'docker build -t bayembacke221/inscription:0.0.1-SNAPSHOT . -f "service-inscription"'
            }
        }
        stage('login docker') {

             steps {
                bat 'docker login -u "bayembacke221" -p "dckr_pat_hV3vs_E02ff-TxRCVaHrGz2vBC4"'
            }
        }
        stage('Push image to docker hub'){
            steps{
                bat 'docker psuh bayembacke221/inscription:0.0.1-SNAPSHOT -f "service-inscription"'
            }
        }
        stage('Approve Deployment') {
              input {
                message "Do you want to proceed for deployment?"
              }
              steps {
                sh 'echo "Deploying into Server"'
              }
        }**/
    }


}