pipeline{
    agent any
    tools{
        maven "3.9.4"
    }
    stages{
        stage('Source') {
            steps{
                git branch: 'main', url: 'https://github.com/bayembacke221/microservice-docker-cicd-kubernetes.git'
            }
        }
        stage ('Build') {
            steps{
                bat 'mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -f "service-inscription/pom.xml"'
            }
        }
        stage ('SonarQube Analysis') {
            steps{
                bat 'mvn sonar:sonar -f "service-inscription/pom.xml"'
            }
        }
    }

}